Assignment-1 Web API Demo (Books API) 05/09/2019
tavisca-nrajpurohit/WebApiDemoBooks pull request #1
Opened 2019-09-05 16:21 UTC by tavisca-nrajpurohit

@tavisca-shitaljit Please review :)

 **GET POST PUT DELETE** on three layers - **API, Service and Data level**. 
Used Json File for **persistent storage** of data. 
Used **custom response object**. 
Written **test cases** for **service layer and data layer** functionality.

2019-09-06 03:04 UTC, tavisca-shitaljit requested changes
Good work.

Let's refactor a bit to see how can we reduce lines of codes and add some more scenarios in test cases.

2019-09-06 03:04 UTC, tavisca-shitaljit commented on WebAPI.Tests/WebAPITest.cs
> +
Instead of count comparison you can compare Id of the returned book

2019-09-06 04:25 UTC, tavisca-nrajpurohit commented on WebAPI.Tests/WebAPITest.cs
> +
Sure, I'll Update that functionality.

2019-09-06 07:09 UTC, tavisca-snarhe commented on WebAPI.Tests/WebAPITest.cs
> +            string msg = response.message;
you can name msg to responseMessage

2019-09-06 07:25 UTC, tavisca-snarhe requested changes

2019-09-06 07:25 UTC, tavisca-snarhe commented on WebAPI.Tests/WebAPITest.cs
> +        public void POST_Input_with_negetive_Id_and_price()
can rename Id to bookId

2019-09-06 07:25 UTC, tavisca-snarhe commented on WebAPI.Tests/WebAPITest.cs
> +        public void POST_Input_With_NON_ALphabet_Book_Title()
why is NON_AL in caps?

2019-09-06 07:25 UTC, tavisca-snarhe commented on WebApiDemo/Model/BookService.cs
> +        private bool isAlphabets(string str)
using regex here will helpfull.

2019-09-06 07:25 UTC, tavisca-snarhe commented on WebApiDemo/Model/BookService.cs
> +        {
construct errors and lastly generate the response with all the errors.

2019-09-06 08:28 UTC, tavisca-nrajpurohit commented on WebAPI.Tests/WebAPITest.cs
> +            string msg = response.message;
sure

2019-09-06 08:29 UTC, tavisca-nrajpurohit commented on WebAPI.Tests/WebAPITest.cs
> +        public void POST_Input_with_negetive_Id_and_price()
sure

2019-09-06 08:29 UTC, tavisca-nrajpurohit commented on WebAPI.Tests/WebAPITest.cs
> +        public void POST_Input_With_NON_ALphabet_Book_Title()
thanks for pointing this out.

2019-09-06 08:29 UTC, tavisca-nrajpurohit commented on WebApiDemo/Model/BookService.cs
> +        private bool isAlphabets(string str)
sure

2019-09-07 11:16 UTC, tavisca-nrajpurohit commented
Updated code with necessary changes. and also updated functionality for  returning relevant status codes from the API

2019-09-07 11:16 UTC, closed without merging